


development:
  adapter: postgresql
  database: camvy_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: camvy_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: camvy_production
  pool: 5
  timeout: 5000